version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - ls $source_directory/*
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - $source_directory/*